name: Build documentation

on:
  pull_request:
  workflow_call:

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3 # check out this repo

      - name: Build docs
        run: |
          cd docs
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/build