name: Build documentation
on:
  push:
    branches:
      - test

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docusaurus BuildDeploy Action
        uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: docs
          git-user: docusaurus
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages